// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_name_ from "./routes/[name].tsx";
import * as $_app from "./routes/_app.tsx";
import * as $aboutme from "./routes/aboutme.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $index from "./routes/index.tsx";
import * as $pages_blog_id_ from "./routes/pages/blog/[id].tsx";
import * as $pages_blog_page_number_ from "./routes/pages/blog/page/[number].tsx";
import * as $Counter from "./islands/Counter.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/[name].tsx": $_name_,
    "./routes/_app.tsx": $_app,
    "./routes/aboutme.tsx": $aboutme,
    "./routes/api/joke.ts": $api_joke,
    "./routes/index.tsx": $index,
    "./routes/pages/blog/[id].tsx": $pages_blog_id_,
    "./routes/pages/blog/page/[number].tsx": $pages_blog_page_number_,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
